spring:
  datasource:
    url: jdbc:mysql://localhost:13306/subway?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:/schema.sql
      mode: always